# Generated by Django 3.2.4 on 2021-06-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(default=None, max_length=20)),
                ('MessageForm', models.TextField()),
            ],
        ),
    ]
