# Generated by Django 3.2.4 on 2021-06-10 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageform',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
