# Generated by Django 3.2.4 on 2021-06-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_messageform_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageForm',
            new_name='ContactForm',
        ),
    ]
