# Generated by Django 3.2.4 on 2021-06-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main_app', '0005_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserS',
        ),
    ]
