# Generated by Django 3.2.4 on 2021-06-25 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.Utility.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.TextField()),
                ('projectDescription', models.TextField()),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amountType', models.IntegerField(default=0)),
                ('projectBudget', models.FloatField()),
                ('finalDate', models.DateTimeField()),
                ('files', main_app.Utility.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
